### ISSUE TITLE
Pdf

### ISSUE THREAD

**Issue by Danielmb87** [zhongwen-dictionary/zhongwen#15]
Thank you so much for a great plugin!

Up until about a month ago, it was possible to use the plugin in pdf files, when opened in the browser. This does not work any more (have tried on different systems and browsers). This function was incredibly useful. If possible, could this please be brought back!

Regards,
Daniel

**Comment by leezu** [comment]
Hello Daniel, thanks for reporting the issue! Could you clarify if an update of the addon or an update of Firefox caused the issue? Could you link an example pdf document for which the addon was working before?

**Comment by Danielmb87** [comment]
Well, unfortunately I'm not sure, due to a few factors.

Both your plugin an perapera used to work on all PDFs that have the text layer. However, both stopped working in PDFs at the same time, which would suggest a browser update was the problem. I therefore downloaded chromium (used to work in that browser too).

Therefore I thought the problem might be due to a Linux update, so tried it on my work Mac (used to work across os:s), but no luck.

Therefore, I'm not quite sure where the issue originates. I'm hoping someone with better knowledge of how the plugin actually functions might have a better chance of figuring out what has changed.

As to PDFs, I mostly use it for on the fly translations when reading Chinese research papers, so I think it would be illegal for me to upload documents I know it has worked on in the past. However, my experience with using it suggests that any PDF that contains text (not just a photocopied image) worked before. Exporting some random characters as PDF should work as a test document.

Please advise on any further information needed or anything else I could do to help get this function back, and again, thank you for such a great plugin!

**Comment by cschiller** [comment]
Hi Daniel,

Zhongwen itself only works with underlying HTML files. It never worked with PDF files. However, if you manage to convert your PDF files to HTML somehow then you can also use Zhongwen on the converted files. I have actually done this myself. One thing to note is that you might have to give Zhongwen permission to access files on your local file system, if that's where your converted PDF files are stored. At least this is necessary for the Chrome version of Zhongwen.
