### ISSUE TITLE
Chinese-Chinese dictionary?

### ISSUE THREAD

**Issue by p2635** [zhongwen-dictionary/zhongwen#17]
I'm looking for Chinese to Chinese Dict and this is the closest addon I could find, can anyone help?

**Comment by leezu** [comment]
Are you aware of any appropriately licensed Chinese to Chinese Dictionary? If so it is feasible to provide a Chinese to Chinese version of this addon.

I have used the Chinese to Chinese dictionary on an Amazon Kindle before. But I am not sure what that dictionary is based on and if it is allowed to redistribute a modified version as part of this addon.

If you don't have any other dictionaries in mind, and if indeed redistribution of that Kindle dictionary is disallowed, we could still provide some script for users to build the Firefox addon locally based on that Kindle addon. Just redistribution via addons.mozilla.org would not be possible.

**Comment by p2635** [comment]
Hi Leezu, I found some stuff here: http://download.huzheng.org/zh_CN/. Seems to be simplified though and I'm not sure if I can find Traditional stuff. Maybe wiktionary has something. I will maybe look later.

**Comment by cschiller** [comment]
Hi p2635,

you'll need to find a dictionary which has the format used by Zhongwen: https://cc-cedict.org/wiki/format:syntax

Unfortunately, Zhongwen is not going to support this, though. You will need to fork the code and tweak it so it fits your needs.

Good luck!
