### ISSUE TITLE
Synchronous XMLHttpRequests

### ISSUE THREAD

**Issue by leezu** [zhongwen-dictionary/zhongwen#2]
https://xhr.spec.whatwg.org/#synchronous-flag:
> Synchronous XMLHttpRequest outside of workers is in the process of being removed from the web platform as it has detrimental effects to the end user’s experience. (This is a long process that takes many years.) Developers must not pass false for the async argument when current global object is a Window object. User agents are strongly encouraged to warn about such usage in developer tools and may experiment with throwing an InvalidAccessError exception when it occurs. 

This affects the fileRead function in dict.js

**Comment by cschiller** [comment]
This has been fixed already.
